// This file is automatically generated by the Firebase setup.
// Do not edit this file manually.

export const firebaseConfig = {
  "projectId": "studio-7907390526-508e3",
  "appId": "1:591025345708:web:3ecf0024f008996d8abb09",
  "apiKey": "AIzaSyDG3Xlfzln_FqyKwAHGTVhlMtjz1VnLzA4",
  "authDomain": "studio-7907390526-508e3.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "591025345708",
  storageBucket: "studio-7907390526-508e3.appspot.com"
};
