import type { Metadata } from "next";
import { Noto_Sans_Lao } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toaster";

const noto_sans_lao = Noto_Sans_Lao({
  subsets: ["lao"],
  variable: "--font-sans-lao",
  weight: ['400', '700']
});

export const metadata: Metadata = {
  title: "Tour Calculator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="lo">
      <body
        className={cn(
          "min-h-screen bg-background font-sans-lao antialiased",
          noto_sans_lao.variable
        )}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
